data:
  num_classes: 2
  ignore_label: 255
  training_size: 19132

train:
  seed: 1588147245
  deterministic: False

dataset:
  name: erasor_carla
  root: /ws/data/erasor_carla/carla_dataset
  num_points: 480000
  voxel_size: 0.1

num_epochs: 5
batch_size: 2

criterion:
  name: focal_loss
  ignore_index: 255

optimizer:
  name: sgd
  lr: 2.4e-1
  weight_decay: 1.0e-4
  momentum: 0.9
  nesterov: true

scheduler:
  name: cosine_warmup

visualize: True
